apiaryio/polls-api

polls/resource.py
Links in HAL are a JSON object with a href to the URI and not a string representing the URI. This pull request fixes that mistake.
=> [HAL] Correctly serialse self link

circle.yml
Otherwise Circle CI will run it's default Django runner which for some reason fails (trying to move a file that doesn't exist). Seems like a Circle CI bug.
=> [CirleCI] Override default tests runner

polls/settings.py, requirements.txt
I do not know if this is the best way to make it.
Anyway with this small change, CORS test passes.
Should close #5 
@honzajavorek ?
=> Added cors headers support

circle.yml, polls/tests.py, polls/views.py
This adds tests, and logic so that when someone tries to create an identical question with the same choices using the API. We will no longer create a duplicate and instead return the same question as before.
Mostly due to many people hitting "try-it" on Apiary for the default question.
=> Prevent a user creating two identical questions

polls/features.py, polls/resource.py, polls/views.py, requirements.txt
This pull request brings support for LaunchDarkly. It's not enabled by default, and it's only available once you configure `LD_API_KEY` in your environment. It will use the following keys from LaunchDarkly (you probably want to add these your own account):
- `question.create`
- `question.delete`
- `choice.vote`
The client will send the user's IP address, hashed via SHA1 to launch darkly as the user. Allowing you to rollout features for individual IPs etc.
/cc @fosrias
=> Use LaunchDarkly when API Key is available

polls/models.py, polls/tests.py, polls/views.py
This also has a side-effect of increasing the performance since we're not performing a count query for each choice, but instead an aggregate query.
=> Order choices by vote count

polls/management/commands/cleanup.py
This pull request introduces a new command to delete questions older than an hour which are not created by the initial seed data.
```bash
$ python manage.py cleanup
Deleting 5 questions
```
This will be scheduled on Heroku to be ran every hour to cleanup user submitted data older than an hour.
/cc @XVincentX
=> Introduce a cleanup command to delete old questions

polls/resource.py, polls/tests.py
This pull request adds an "allow" header showing the available methods that are applicable to the resource when not using Siren. This allows you to determine available transitions when using the JSON or HAL content types which didn't offer these before.
Example usage can be found in Hyperdrive: https://github.com/the-hypermedia-project/Hyperdrive/pull/15
=> Add an allow header to JSON responses

README.md
- Mention that pip and virtualenv are prerequisites along with linking to their installation pages.
- Include instructions to run dredd.
=> Improve installation instructions on the README

polls/resource.py
Since the specification for HAL is registered with IANA, it should therefore support the IANA assigned content type, including the `vnd.` prefix.
- http://www.iana.org/assignments/media-types/application/vnd.hal+json
- http://www.iana.org/assignments/media-types/application/vnd.hal+xml
=> Support vnd.hal+json content type

README.md
This pull request changes the order of the sections to move the docker Heroku instructions to the bottom of the README. The Heroku button and simpler instructions have been moved above the docker instructions. I don't think we should be putting docker right at the top as this alternate installation instructions are far more complicated than the simple Heroku button ones. We should keep this simple for the average user who probably doesn't want to play around with the Polls API in docker.
I've also moved running the local development environment higher in the README above the instructions to deploy to Heroku. I believe people will probably want to play around with it locally before deploying it elsewhere and these instructions are more important.
=> Rearrange order of sections in README

app.json
The Python build pack has started, by default running `python manage.py collectstatic` for all Django apps, even if they don't use the collectstatic Django app (which we don't). This causes the Heroku button to fail since it runs collectstatic which isn't used.
```
$ python manage.py collectstatic --noinput
Unknown command: 'collectstatic'
Type 'manage.py help' for usage.
!     Error while running '$ python manage.py collectstatic --noinput'.
See traceback above for details.
You may need to update application code to resolve this error.
Or, you can disable collectstatic for this application:
$ heroku config:set DISABLE_COLLECTSTATIC=1
http://devcenter.heroku.com/articles/django-assets
!     Push rejected, failed to compile Python app
```
This pull request disables it entirely.
/cc @abtris
=> Disable collect static in Python buildpack

scripts/dredd
Changes in the Dredd docker image https://github.com/apiaryio/docker-base-images/pull/51 seemed to changed the docker image to make the `dredd` command no longer work.
Current master is failing because `dredd` is not found.
/cc @abtris
=> Make dredd runner compatible with docker image

scripts/dredd
Reverts apiaryio/polls-api#41
Since #41 was created, https://github.com/apiaryio/docker-base-images/pull/60 was also merged solving the problem upstream in the Docker image.
=> Revert "Make dredd runner compatible with docker image"

polls/resource.py, polls/tests.py, polls/views.py
Unknown page `GET /questions?page=10000` and questions that don't exist `GET /question/10000` would cause unhandled errors and return 500 error to a user. This PR adds handling and returns a 404 in these cases.
=> Return 404 instead of 500 for not found

polls/management/commands/cleanup.py
When I updated to Django 1.9 in #42, the location of the fixture changed due to changes in Django 1.9. The cleanup script was never updated and thus fails when ran:
```
$ heroku run python manage.py cleanup -a pollsapi
▸    heroku-cli: update available from 6.13.4 to 6.14.39-addc925
Running python manage.py cleanup on ⬢ pollsapi... up, run.9999 (Standard-1X)
Traceback (most recent call last):
File "manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
utility.execute()
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File …
```
=> Update location to initial data in cleanup command

polls/features.py, requirements.txt
Launch Darkly is unused and undocumented and for maintainability can be
removed.
The previously used version no longer works with pip10.
=> Remove launch darkly

Pipfile, Pipfile.lock, polls/tests.py, polls/views.py
Some invalid inputs such as incorrect data types caused 500 errors due to invalid input into database.
I'm using jsonschema to achieve this, the jsonschema 2.6.0 library has approval in TPLTA
=> Validate entire request body when creating questions

polls/tests.py, polls/views.py
When a user votes for a choice that doesn't exist, before a DoesNotExist exception was being raised causing a 500. This should be caught and return a 404 to the user.
=> Return 404 when voting for a choice that doesnt exist

docker-compose.yml
In prior pull requests the working directory in Dockerfile became inconsistent with docker-compose.yaml and thus when you run a command in docker-compose the wd is incorrect and prevents you running the application.
=> Fix incorrect working directory in docker compose

dredd.yml, polls/resource.py, polls/tests.py
When the accept header doesn't contain a sub-type negotiatior will raise a ValueError resulting in a 500 status. For example:
```
$ curl http://127.0.0.1:8000/ -H 'Accept: application'
<h1>Server Error (500)</h1>
```
```
Internal Server Error: /
Traceback (most recent call last):
File "/Users/kyle/.local/share/virtualenvs/polls-api-n-94SdNq/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/Users/kyle/.local/share/virtualenvs/polls-api-n-94SdNq/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = self._get_response(request)
File "/Users/kyle/.local/share/virtualenvs/polls-api-n-94SdNq/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response …
```
=> Handle accept header without subtype

Pipfile, Pipfile.lock
psycopg2 is renamed to psycopg2-binary
http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/
Closes #65
=> Update to psycopg2-binary

Pipfile, Pipfile.lock, polls/resource.py
Negotiator is problematic for a couple of reasons:
* It is unlicensed
* It doesn't support Python 3.x
* Maintainer is not supporting the library (last release in 2012)
This update will allow us to move to Python 3.
=> Use mimeparse over negotiator

.circleci/config.yml, Dockerfile, Pipfile, Pipfile.lock, polls/resource.py, polls/tests.py, polls/views.py
Most change in diff will be wrapping `map` result in `list`, in Python 3 map returns a generator instead of a list.
=> Update to Python 3.7

polls/tests.py, polls/urls.py
The API returns the stauts of the API, which is always healthy if the success made it through. This follows the design of RFC 8259 (https://health15.docs.apiary.io/#reference/0/health-check/health-check)
=> Add /healthcheck

dredd.yml, polls/settings.py, polls/tests.py
This changeset makes the API redirect non TLS traffic to HTTPS using the `SECURE_SSL_REDIRECT` option in Django with the security middleware.
I've had to update all the tests to behave like they are https using `secure=True` option for the test client, otherwise all test responses would be a redirect and fail. Similiary, Dredd operates without `SECURE_SSL_REDIRECT`.
=> Redirect to HTTPS when using HTTP

polls/management/commands/cleanup.py
The cleanup script deletes all the non-fixture questions, however it still leaves around potentially tens of thousands of votes on the fixture questions.
This changeset adds an additional step to the cleanup script to remove all votes.
```
>>> Vote.objects.count()
33304
```
=> Allow cleanup script to delete votes

polls/settings.py
This changeset adds the following header:
```
X-Frame-Options: DENY
```
As part of OWASP secure headers where the absence of this header can failing report (https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers).
> The page cannot be displayed in a frame, regardless of the site attempting to do so.
=> Add X-Frame-Options header as per OWASP report

polls/resource.py, polls/tests.py
The code would throw a ValueError (since a string isn't number) and result in a 500.
=> Return 404 when page is not a number

polls/tests.py, polls/views.py
Failing test demonstrating problem, deleting a question raises `Question.DoesNotExist` which is not caught for the DELETE code path. To reproduce:
```
$ curl <service>/questions/1000000
```
```
$ python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...............E.....
======================================================================
ERROR: test_unfound_page_delete (polls.tests.QuestionDetailTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/kyle/Projects/apiaryio/polls-api/polls/tests.py", line 191, in test_unfound_page_delete
response = self.client.delete('/questions/1', secure=True)
File …
```
=> Return 404 when deleting unknown question
